version: '{build}'

pull_requests:
    do_not_increment_build_number: true

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  api_key:
    secure: eaiytjZ8451bGqdim49VhzfsYNDviMmEm/lMbc34oqmznMUEb0BW/9/yFckWyzf1

build_script:
- ps: .\build.ps1

test: off

artifacts:
- path: .\azure-file-uploader-*.zip
  name: Archive

deploy:
  # All builds go to myget
- provider: GitHub
  auth_token:
    secure: wyRf/wHvY67t+0Lni9CUlbQ77RpieO1OOAN4f47vSwqgxAx9KCfAlH6iMbJYl4xh
  artifact: /azure-file-uploader-.*\.zip/
  on:
    branch: master
    appveyor_repo_tag: true
  